apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog

bases:
- ../../../../environments/overlays/3scale

resources:
- api-url-config-sealed-secret.yaml

patchesStrategicMerge:
- patch.yaml

patchesJson6902:
  - path: patch-tls-termination.yaml
    target:
      group: route.openshift.io
      version: v1
      kind: Route
      name: apicast-prod
  - path: patch-tls-termination.yaml
    target:
      group: route.openshift.io
      version: v1
      kind: Route
      name: apicast-stage